remote_theme: pages-themes/architect@v0.2.0
title: Servicechain.io
description: Empowering service workers using Distributed Internet Services 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
